### PR TITLE
add option to enable forceReloadOnRedirection

### PR DESCRIPTION
**Pull request by MikkoA**
This an update to: https://github.com/droibit/react-native-custom-tabs/pull/11 to add the suggested option flag.

### CODE REVIEW

**Comment by mhkhung** [comment]
Can this go in soon? We are having the same issue..

**Comment by droibit** [comment]
@MikkoA   
Thank you for PR.
I am very sorry that the merge is delayed.

**Comment by jdnichollsc** [comment]
Hi guys!
I can see the browser opened outside the app in some Android devices when this property is true, is that behavior as expected?

**Comment by risingworld777** [comment]
@droibit I installed latest version 0.1.7.  But I can't see update of this PR.

**Pull request merged**
