### PR TITLE
Fixed issue with android build for RN >= 0.60

### PR DESCRIPTION
**Pull request by abhaynpai**
`react-native-custom-tabs` was causing an issue with RN >= 0.60. This PR fixes the issue.

### CODE REVIEW

**Comment by abhaynpai** [comment]
@droibit - Can we merge this PR?

**Comment by sattaman** [comment]
+1

**Comment by manjeets12** [comment]
+1

**Comment by subinsuresh991** [comment]
@abhaynpai  What was the issue? I am getting an error like "Cannot read property OpenURL. of undefined"

**Comment by abhaynpai** [comment]
Hey @subinsuresh991. This was mainly to fix issue with the build. I am unsure on why you're getting OpenURL of undefined. Did you check with the URL that you are passing into the function?

PS: It's quite sad to see that this repository is dead for 2 years now and @droibit is not taking any actions to merge the PRs.

**Pull request closed without merging**
